name: SQL Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.x'
    - name: Lint check
      run: ruby lib/main.rb
